import { PrivacyLaw, LawComparison } from '@/app/types/privacy-law';

// Texas Instruments operating regions:
// US, UK, Germany, India, China, Mexico, Canada, Austria, Czech Republic, Denmark,
// Finland, Israel, France, Hungary, Italy, Netherlands, Norway, Poland, Switzerland,
// Japan, Malaysia, Philippines, South Korea, Taiwan

export const privacyLaws: PrivacyLaw[] = [
  {
    id: 'gdpr',
    name: 'GDPR',
    jurisdiction: 'European Union',
    enactedYear: 2018,
    scope: 'Comprehensive data protection framework',
    keyFeatures: ['Right to Access', 'Right to Erasure', 'Data Portability', 'Consent Requirements'],
    applicability: 'All personal data processing of EU residents',
    referenceUrl: 'https://gdpr-info.eu/',
  },
  {
    id: 'ccpa',
    name: 'CCPA',
    jurisdiction: 'California, USA',
    enactedYear: 2020,
    scope: 'Consumer privacy rights for California residents',
    keyFeatures: ['Right to Know', 'Right to Delete', 'Right to Opt-Out', 'Data Disclosure'],
    applicability: 'Personal information of California residents',
    referenceUrl: 'https://oag.ca.gov/privacy/ccpa',
  },
  {
    id: 'pipeda',
    name: 'PIPEDA',
    jurisdiction: 'Canada',
    enactedYear: 2000,
    scope: 'Personal information protection and electronic documents',
    keyFeatures: ['Accountability', 'Transparency', 'Individual Access', 'Accuracy'],
    applicability: 'Personal information held by private sector organizations',
    referenceUrl: 'https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/',
  },
  {
    id: 'dpa_uk',
    name: 'UK-DPA 2018',
    jurisdiction: 'United Kingdom',
    enactedYear: 2018,
    scope: 'Data Protection Act 2018 and UK GDPR',
    keyFeatures: ['Right to Access', 'Right to Erasure', 'Data Portability', 'Lawful Basis'],
    applicability: 'Personal data processing of UK residents',
    referenceUrl: 'https://ico.org.uk/for-organisations/data-protection-act-2018/',
  },
  {
    id: 'vcdpa',
    name: 'VCDPA',
    jurisdiction: 'Virginia, USA',
    enactedYear: 2023,
    scope: 'Virginia Consumer Data Protection Act',
    keyFeatures: ['Right to Access', 'Right to Delete', 'Right to Correct', 'Opt-Out'],
    applicability: 'Personal data of Virginia consumers',
    referenceUrl: 'https://www.oag.state.va.us/consumer-protection/privacy/virginia-consumer-data-protection-act',
  },
  {
    id: 'cpa',
    name: 'CPA',
    jurisdiction: 'Colorado, USA',
    enactedYear: 2023,
    scope: 'Colorado Privacy Act',
    keyFeatures: ['Right to Access', 'Right to Delete', 'Right to Opt-Out', 'Data Minimization'],
    applicability: 'Personal data of Colorado residents',
    referenceUrl: 'https://coag.gov/colorado-privacy-act/',
  },
  {
    id: 'appi',
    name: 'APPI',
    jurisdiction: 'Japan',
    enactedYear: 2017,
    scope: 'Act on Protection of Personal Information',
    keyFeatures: ['Consent', 'Purpose Limitation', 'Accuracy', 'Security Measures'],
    applicability: 'Personal information processing by Japan-based organizations',
    referenceUrl: 'https://www.ppc.go.jp/en/about/introduction/appi/',
  },
  {
    id: 'pipa',
    name: 'PIPA',
    jurisdiction: 'South Korea',
    enactedYear: 2011,
    scope: 'Personal Information Protection Act',
    keyFeatures: ['Consent', 'Collection Notice', 'Right to Correction', 'Right to Deletion'],
    applicability: 'Personal information held by Korean organizations',
    referenceUrl: 'https://www.pipc.go.kr/eng/',
  },
  {
    id: 'lpdp_mexico',
    name: 'LPDP',
    jurisdiction: 'Mexico',
    enactedYear: 2010,
    scope: 'Federal Law for Protection of Personal Data',
    keyFeatures: ['Consent', 'Purpose Limitation', 'Data Minimization', 'Right to Access'],
    applicability: 'Personal data processing in Mexico',
    referenceUrl: 'https://www.inai.org.mx/?page_id=11230',
  },
  {
    id: 'cpra',
    name: 'CPRA',
    jurisdiction: 'California, USA',
    enactedYear: 2023,
    scope: 'California Privacy Rights Act (CCPA amendment)',
    keyFeatures: ['Right to Correct', 'Right to Limit Use', 'Automated Decision Opt-Out', 'Data Minimization'],
    applicability: 'Consumer personal information in California',
    referenceUrl: 'https://oag.ca.gov/privacy/cpra',
  },
  {
    id: 'dpdp',
    name: 'DPDP Act',
    jurisdiction: 'India',
    enactedYear: 2023,
    scope: 'Digital Personal Data Protection Act',
    keyFeatures: ['Consent', 'Right to Access', 'Right to Correction', 'Data Minimization'],
    applicability: 'Personal data processing by entities in India',
    referenceUrl: 'https://www.meity.gov.in/data-protection-framework',
  },
];

export const featureComparison: LawComparison[] = [
  {
    attribute: 'Right to Access',
    GDPR: true,
    CCPA: true,
    PIPEDA: true,
    'UK-DPA 2018': true,
    VCDPA: true,
    CPA: true,
    APPI: true,
    PIPA: true,
    LPDP: true,
    CPRA: true,
    'DPDP Act': true,
  },
  {
    attribute: 'Right to Erasure/Deletion',
    GDPR: true,
    CCPA: true,
    PIPEDA: false,
    'UK-DPA 2018': true,
    VCDPA: true,
    CPA: true,
    APPI: false,
    PIPA: true,
    LPDP: false,
    CPRA: true,
    'DPDP Act': false,
  },
  {
    attribute: 'Data Portability',
    GDPR: true,
    CCPA: false,
    PIPEDA: false,
    'UK-DPA 2018': true,
    VCDPA: false,
    CPA: false,
    APPI: false,
    PIPA: false,
    LPDP: false,
    CPRA: true,
    'DPDP Act': false,
  },
  {
    attribute: 'Explicit Consent Required',
    GDPR: true,
    CCPA: false,
    PIPEDA: false,
    'UK-DPA 2018': false,
    VCDPA: false,
    CPA: false,
    APPI: true,
    PIPA: true,
    LPDP: true,
    CPRA: false,
    'DPDP Act': true,
  },
  {
    attribute: 'Data Protection Officer Required',
    GDPR: true,
    CCPA: false,
    PIPEDA: false,
    'UK-DPA 2018': false,
    VCDPA: false,
    CPA: false,
    APPI: false,
    PIPA: false,
    LPDP: false,
    CPRA: false,
    'DPDP Act': false,
  },
  {
    attribute: 'Cross-Border Restrictions',
    GDPR: true,
    CCPA: false,
    PIPEDA: false,
    'UK-DPA 2018': true,
    VCDPA: false,
    CPA: false,
    APPI: false,
    PIPA: false,
    LPDP: false,
    CPRA: false,
    'DPDP Act': false,
  },
  {
    attribute: 'Purpose Limitation',
    GDPR: true,
    CCPA: false,
    PIPEDA: true,
    'UK-DPA 2018': true,
    VCDPA: false,
    CPA: true,
    APPI: true,
    PIPA: true,
    LPDP: true,
    CPRA: false,
    'DPDP Act': true,
  },
  {
    attribute: 'Right to Correct/Rectify',
    GDPR: true,
    CCPA: false,
    PIPEDA: true,
    'UK-DPA 2018': true,
    VCDPA: true,
    CPA: false,
    APPI: false,
    PIPA: true,
    LPDP: false,
    CPRA: true,
    'DPDP Act': true,
  },
];
